### ISSUE TITLE
Include, for nested api

### ISSUE THREAD

**Issue by cconnerj** [ga-wdi-exercises/project3#467] opened 2017-05-12 13:10 UTC
https://github.com/zonekid/Delmarvalous

running error-----uninitialized constant Category::Species 

def index
  @categories= Category.all

  respond_to do |format|
    format.json { render json: @categories, include: :species }
  end
end

i believe it may have to do with our models, but they seem to be alright, cant find the problem

**Comment by AndyWhitley** [comment] 2017-05-12 13:29
Interesting. Is the code on GitHub up to date / should I be looking at a particular branch?

**Comment by cconnerj** [comment] 2017-05-12 13:30
look at the conner branch

**Comment by AndyWhitley** [comment] 2017-05-12 13:30
lowercase conner?

**Comment by cconnerj** [comment] 2017-05-12 13:31
yes

**Comment by cconnerj** [comment] 2017-05-12 13:32
wait! i need to push changes hah sorry

**Comment by cconnerj** [comment] 2017-05-12 13:33
ok you are clear to go!

**Comment by AndyWhitley** [comment] 2017-05-12 13:37
I'm not seeing the update on GitHub, you sure the push went through?

**Comment by cconnerj** [comment] 2017-05-12 13:42
Ok! i got it pushed, i know we may get errors on app.js, but just focusing on the rails api nesting

**Comment by AndyWhitley** [comment] 2017-05-12 13:46
One problem I'm seeing is that I can't get the migrations to run. This is because in the first migration, the one that defines the Species table, you reference (via a foreign key) :category. The problem is that, at that time, the table categories doesn't exist (since that migration runs after). You need to reorder your migrations (delete the file for create_species and remake it)

**Comment by AndyWhitley** [comment] 2017-05-12 13:47
@cconnerj Nevermind, I see that you fixed it in the latest commits I just pulled down. One sec...

**Comment by AndyWhitley** [comment] 2017-05-12 13:56
@cconnerj This is an edge-case where ActiveRecord is trying to help you out. The singular and plural, in this case, are both 'Species'. And while you followed the correct way for normal nouns, ActiveRecord has some cases of singular / plural matches built in. So if you change the filename to `species.rb` and the class name inside of that file to `Species`, it will fix everything.

**Comment by AndyWhitley** [comment] 2017-05-12 13:56
If that fixes the problem, please go ahead and close this issue.

**Comment by twelve13** [comment] 2017-05-12 13:57
ah just curious - is category/categories one of those built in things?

**Comment by twelve13** [comment] 2017-05-12 13:58
yay that fixed it!  thanks

**Comment by AndyWhitley** [comment] 2017-05-12 14:43
@twelve13 Yep, that's another example of preset pluralizations in AR

**Closed as completed** 2017-05-12 14:44 UTC
