### ISSUE TITLE
Routing and Schema Issues

### ISSUE THREAD

**Issue by alman92** [ga-wdi-exercises/project3#316] opened 2016-11-02 15:13 UTC
Some background:  Met with Jesse to link comments in rails to angular app, need to change around a few things before starting on checklist and unsure where to start coding wise.

Right now, my routes are set as such.  
![image](https://cloud.githubusercontent.com/assets/19317100/19934138/08494abc-a0ec-11e6-8e8b-2fe0b8f1e225.png)
I need destination to have many comments, and passport to have many comments.  I also need to add the option to choose the destination name in a comment in a dropdown menu (collection-select?) so I'm confused as to how to change the schema to reflect that.  I also need to add a passport_id to the comments.  These seems to me like it should be triple nested so I'm a little confused as to how to move forward.

![image](https://cloud.githubusercontent.com/assets/19317100/19934368/c65e77f2-a0ec-11e6-8e66-bbab2b6c3be7.png)

These are my current migrations and my schema.  I need to rework them.  I'm feeling pretty overwhelmed just starting off and need some guidance!

**Comment by jshawl** [comment] 2016-11-02 15:31
todo list had seeds before routes ...

**Comment by nolds9** [comment] 2016-11-02 15:31
looks like your `comments` table is missing a `passport_id`, you will need to add the column in

**Comment by nolds9** [comment] 2016-11-02 15:34
assuming you have already created your `comments` table, you can do this by generating another migration and utilizing the `add_column` method

**Comment by alman92** [comment] 2016-11-02 18:14
Hey ok I've been moving on and I ran into this rails error.

![image](https://cloud.githubusercontent.com/assets/19317100/19941492/ab9d69b8-a106-11e6-9614-1c3b68e39fe7.png)

![image](https://cloud.githubusercontent.com/assets/19317100/19941444/7e6b5e28-a106-11e6-9ad8-eea32bac266e.png)

![image](https://cloud.githubusercontent.com/assets/19317100/19941455/914a9ec8-a106-11e6-98a0-822bb46f710a.png)

Kind of stuck on where to go...

**Comment by nolds9** [comment] 2016-11-02 18:17
@alman92 are you sure there is a Destination with the id of 1. What I would do is go into the rails console, and re enact the queries there to make sure it is not a data issue.

**Comment by alman92** [comment] 2016-11-02 18:24
Cool, just needed to drop and redo the DB

**Comment by alman92** [comment] 2016-11-02 18:26
Is the Index alright in my controller up there?

**Comment by amaseda** [comment] 2016-11-02 18:31
Index looks good to me if you're trying to send all comments that belong to a particular destination back in JSON form!

**Comment by alman92** [comment] 2016-11-02 18:39
![image](https://cloud.githubusercontent.com/assets/19317100/19942426/1153a8dc-a10a-11e6-9748-32174d7204bf.png)

I think this goes back to the original routing problem I'm confused about -_-

**Comment by jshawl** [comment] 2016-11-02 18:39
can we see `config/routes.rb`?

**Comment by alman92** [comment] 2016-11-02 18:40
![image](https://cloud.githubusercontent.com/assets/19317100/19942480/49583c5c-a10a-11e6-90a0-c0d40f1e2ceb.png)

**Comment by jshawl** [comment] 2016-11-02 18:41
looks lik you have typo in url - destinatons

**Comment by jshawl** [comment] 2016-11-02 18:41
config/routes looks good

**Comment by alman92** [comment] 2016-11-02 18:42
I don't see the typo(?) in the URL?

**Comment by jshawl** [comment] 2016-11-02 18:42
I think you typed in the url incorrectly in your browser:

![](https://cloud.githubusercontent.com/assets/19317100/19942426/1153a8dc-a10a-11e6-9748-32174d7204bf.png)

**Comment by alman92** [comment] 2016-11-02 18:43
Oh right fixed it, ok im back to this one.

![image](https://cloud.githubusercontent.com/assets/19317100/19942612/b62ad3e4-a10a-11e6-98b9-f05511e431be.png)

**Comment by alman92** [comment] 2016-11-02 18:44
Should passports and destinations be singular?

**Comment by nolds9** [comment] 2016-11-02 18:46
@alman92 you have multiple routes that map to the same controller action.

I.e `/passports/:passport_id/destinations` and `/destinations` both map to `destinations#index`

My recommendation would be to choose one of those

**Comment by alman92** [comment] 2016-11-02 18:48
How do I choose one...?

**Comment by alman92** [comment] 2016-11-02 18:49
I kind of need both of them to map to destinations

**Comment by jshawl** [comment] 2016-11-02 18:49
@alman92 did you create seeds?

**Comment by alman92** [comment] 2016-11-02 18:57
Comment.create({passport:Passport.first, destination:Destination.first, body: "The Border sucked!"})

What were using for seeds just to test

**Comment by jshawl** [comment] 2016-11-02 18:58
did it work with `rails db:seed` ?

**Comment by alman92** [comment] 2016-11-02 18:58
NOT THAT

Comment.create({passport_id:Passport.first, destination_id:Destination.first, body: "The Border sucked!"})

this

**Comment by alman92** [comment] 2016-11-02 18:58
Yea it worked

**Comment by jshawl** [comment] 2016-11-02 18:59
If so, this indicates a url structure like this:

```
resources :passports do
  resources :destinations
  resources :comments
end
```

**Comment by alman92** [comment] 2016-11-02 19:00
Ok that's what I had yesterday.  Can I change it back to that and get rid of the second set of routes here?

![image](https://cloud.githubusercontent.com/assets/19317100/19943279/0d842c56-a10d-11e6-8115-a66d8a6389ab.png)

**Comment by jshawl** [comment] 2016-11-02 19:02
try it out!

**Comment by alman92** [comment] 2016-11-02 19:03
![image](https://cloud.githubusercontent.com/assets/19317100/19943364/7c02f2b6-a10d-11e6-96e1-98ea84f1ce9e.png)
Back to this error

**Comment by amaseda** [comment] 2016-11-02 19:06
What's the output of `rails routes` now?

**Comment by alman92** [comment] 2016-11-02 19:08
Im trying to get to the destinations index for the first passport so I did.

http://localhost:3000/passports/1/destinations

**Comment by alman92** [comment] 2016-11-02 19:08
![image](https://cloud.githubusercontent.com/assets/19317100/19943548/42a25dc6-a10e-11e6-8783-969a029ea3c7.png)

**Comment by jshawl** [comment] 2016-11-02 19:09
that looks good

**Comment by jshawl** [comment] 2016-11-02 19:11
are you clikcing on a link or is it a redirect that's sending you to `/destinations`?

**Comment by alman92** [comment] 2016-11-02 19:15
In the app it would be clicking on a link

**Comment by jshawl** [comment] 2016-11-02 19:16
are you linking to `/destinations`?

**Comment by alman92** [comment] 2016-11-02 19:17
How do I determine that?

**Comment by jshawl** [comment] 2016-11-02 19:19
where did you cick the link that took you to `/destinations`?

**Comment by alman92** [comment] 2016-11-02 19:20
I haven't clicked anything I'm only working on the backend, its not connected to the front end yet.

**Comment by jshawl** [comment] 2016-11-02 19:22
> In the app it would be clicking on a link

https://github.com/ga-wdi-exercises/project3/issues/316#issuecomment-257969913

**Comment by jshawl** [comment] 2016-11-02 19:23
so i think the issue is solved?!

**Comment by alman92** [comment] 2016-11-02 19:30
Ok now I'm back here

![image](https://cloud.githubusercontent.com/assets/19317100/19944178/18fe10de-a111-11e6-96e2-355f4507f03f.png)

Its saying there is no passport with an id of 1 which there is and there was like 5 minutes ago.

**Comment by jshawl** [comment] 2016-11-02 19:35
ok excellent! open up rails console.

What is the output of `Passport.first`

**Comment by alman92** [comment] 2016-11-02 19:35
![image](https://cloud.githubusercontent.com/assets/19317100/19944366/fff3946e-a111-11e6-971b-4f5a62d82501.png)

**Comment by jshawl** [comment] 2016-11-02 19:38
looks like you don't have any passports - `Passport.all.count` should confirm this

**Comment by alman92** [comment] 2016-11-02 19:40
Yea there is none, but we put in that placeholder seed file just to test to see if we can get the comments correct.  If I reseed with my original seeds this would be working.

**Comment by amaseda** [comment] 2016-11-02 20:27
Going to close this one since we just talked about it IRL. But feel free to re-open if you have any more questions.

**Closed as completed by amaseda** 2016-11-02 20:27 UTC
Labels: waiting on student response
